name: GiveLore
main: GiveLore\Main
api: [3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15]
version: 1.0
author: XxBoomer

commands:
 givelore:
    description: "test givelore"
    usage: "/givelore"
    permission: givelore.use


